export const intro = { name: "Karim Khadro", under_name: "I Build Things With Passion", intro_text: "I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at " };
export const menu = { it1: "Profile", it2: "Experiences", it3: "Projects", it4: "Contact" };
export const profile = { name: "Karim Khadro", age: "29/09/1996", location: "Theux, Belgium, Planet Earth", text: "I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at  I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at" }
export const exp = {
    education: [
        { inst_name: "The University of Liège", class_name: "MCs in Computer Science, Intelligent systems ", location: "Liège", starting_date: "Sept 2020", finish_date: "Sept 2021", description: "First year of master in computer science with Intelligent systems option. I learned about Deep learning, Machine learning and increased my programming knowledge. I quit after the first year of the two years and a half program" },
        { inst_name: "The Higher Education Institution of the Province of Liège", class_name: "Bachelor in Computer Science and Management, Intelligent systems ", location: "Seraing", starting_date: "Sept 2016", description: "The education started with basic programming in C then became mainly Java-based programming, but I also learned about SQL, PHP, MVC, UML, C#, JS and more. During my time in college, I specialized in management which allowed me to have some knowledge in the big data field. ", finish_date: "Jan 2020" },
        { inst_name: "Don Bosco Verviers Hight school", class_name: "Computer Technician ", location: "Verviers", starting_date: "Sept 2015", description: "First steps into web programming, computer reperation and computer parts, as well networking and manageniong small networks.   ", finish_date: "Jun 2016" }
    ],
    work: [
        { company_name: "I-pulses   ", job_name: "5th grade ", location: "Verviers", starting_date: "Sept 2015", description: "5th grade high school", finish_date: "Jun 2016" },
        { company_name: "Haute Ecole de la Provaince de Liege", job_name: "5th grade ", location: "Verviers", starting_date: "Sept 2015", description: "5th grade high school", finish_date: "Jun 2016" }]
};
